// Code generated by MockGen. DO NOT EDIT.
// Source: preference/preference.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	preference "github.com/GeovaneCavalcante/ms-notificator/preference"
	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// GetPreferenceByUser mocks base method.
func (m *MockUseCase) GetPreferenceByUser(ctx context.Context, userID string) (*preference.PreferenceNotification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreferenceByUser", ctx, userID)
	ret0, _ := ret[0].(*preference.PreferenceNotification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreferenceByUser indicates an expected call of GetPreferenceByUser.
func (mr *MockUseCaseMockRecorder) GetPreferenceByUser(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreferenceByUser", reflect.TypeOf((*MockUseCase)(nil).GetPreferenceByUser), ctx, userID)
}
